[buildPlans.IosevkaTmq]
family = "Iosevka TMQ"
spacing = "normal"
serifs = "slab"
noCvSs = true
exportGlyphNames = false

[buildPlans.IosevkaTmq.variants.design]
percent = "rings-continuous-slash-also-connected"
one = "base"
brace = "curly"
lig-equal-chain = "without-notch"
lig-hyphen-chain = "without-notch"

  [buildPlans.IosevkaTmq.ligations]
  inherits = "dlig"

[buildPlans.IosevkaTmq.widths.Normal]
shape = 600
menu = 5
css = "normal"
