name: Build Iosevka TMQ Font
on:
  push:
    branches:
      - "master"
        
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  schedule:
    - cron: '0 3 * * *'

jobs:
  build_font:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y git tar nodejs ttfautohint
      - name: Build
        run: ./build.sh
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "Automatic Release"
          files: |
            IosevkaTmq.tar.gz
